# Whether or not to enable invisible slimes for easily seeing invisible item frames
slimes-enabled: true

# The item in the center of the recipe
# Recommended to use "/iframe setitem" to change this
recipe:
  ==: org.bukkit.inventory.ItemStack
  v: 2567
  type: LINGERING_POTION
  meta:
    ==: ItemMeta
    meta-type: POTION
    potion-type: minecraft:invisibility