name: SurvivalInvisiframes
version: ${project.version}
api-version: 1.16
main: com.darkender.plugins.survivalinvisiframes.SurvivalInvisiframes
author: Techdoodle
permissions:
  survivalinvisiframes.place:
    default: true
  survivalinvisiframes.craft:
    default: true